config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # rootはlocalhost:3000にアクセスが来た際のルーティングを指す。
  # 今回はlocalhost:3000mのアクセスが来たらBoardsControllerクラスのindexメソッドを実行するように定義。
  # get 'boards', to: "boards#index"
  # get 'boards/new', to: "boards#new"
  # post 'boards', to: "boards#create"
  # get 'boards/:id', to: "boards#show"

  # resourcesbase routingを使うと全てのrouteを最初から作れる。
  resources :boards

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
# ApplicationContorollerを継承する事でcontorollerとしての役割を持てるっては話
class BoardsController < ApplicationController

    before_action :set_target_board, only: %i[show edit update destroy]

    # BoardsControllerのindexアクションという(メソッドでもある)
    def index
        # 全件取得 TODO(orita)あとで件数取得を制限する
        @board = Board.all
    end

    def new
        # Boardモデルのオブジェクトを作成.インスタンス変数に格納しviewで使えるようにする。
        @board = Board.new
        # binding.pry
    end

    def create
        board = Board.create(board_params)
        # binding pry
        # createした時点でBoardオブジェクトはidを付与され存在している。そこへリダイレクトさせる。
        redirect_to board
    end

    def show
        # idに対応するBoardオブジェクトを取得できる
        # before_actionがあるので @board = Board.find(params[:id]) の記載は不要
        # binding pry
    end

    def edit
        # インスタンス変数に格納してあげる
        # before_actionがあるので @board = Board.find(params[:id]) の記載は不要
    end

    def update
        # boardのparamsを書き換える
        @board.update(board_params)

        # redirect_toメソッドでリダイレクトさせる。特定のmodelのオブジェクト指定にする書き方「/boards/:id」のパスになる。
        redirect_to board
    end

    # 注意：destroyとい関数名はresourcesbase routingにとってはすでに決められた予約語なのでタイポするとエラーでる。
    # もしくはconfig/routeに書くかどっちか。
    def destroy
        @board.delete

        redirect_to boards_path
    end

    private
    def board_params
        params.require(:board).permit(:name,:title,:body)
    end

    def set_target_board
        @board = Board.find(params[:id])
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<%
=begin%>
  cardのコンポーネント再利用:パーシャル
<%
=end%>
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
  </div>
</div>

app/views/boards/_form.html.erb
<%
=begin%>
 パーシャル(コンポーネント再利用はファイル名のprefixに＿をつける) 
<%
=end%>

<%
=begin%>
 以下rails構文 
<%
=end%>
<%= form_for board do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to "一覧" ,boards_path , class:"btn btn-outline-dark" %>
    <%= link_to "編集" ,edit_board_path , class:"btn btn-outline-dark" %>

  </div>
</div>

<%
=begin%>
 以下rails構文 
<%
=end%>

<%= render partial: "form", locals: {board: @board}  %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>ただのやることリスト</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to "新規作成", new_board_path, class: "btn btn-outline-dark" %>
  </div>
</div>
<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @board.each do |board| %>
    <tr>
      <td><%= board.id %></td>
      <td><%= board.title %></td>
      <td><%= board.name %></td>
      <td><%= board.created_at.to_s(:datetime_jp) %></td>
      <td><%= board.updated_at.strftime('%Y年 %m月 %d日 %H時 %M分') %></td>
      <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td> 
      <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
      <%
=begin%>
  link_toメソッドの第二引数にboardを指定すれば、”/boards/:id”のパスを指定できる。
<%
=end%>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to "掲示板一覧" ,boards_path , class:"btn btn-outline-dark" %>
  </div>
</div>

<%
=begin%>
 以下rails構文 
 renderメソッドでpartialを呼ぶ。「_form」を呼ぶには「form」で良い。
 またlocalsでpartialにインスタンス変数を渡さないと、
 このpageからはformパーシャルが@boardありきで動く前提かどうかわからない。
<%
=end%>

<%= render partial: "form", locals: {board: @board}  %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to "掲示板一覧" ,boards_path , class:"btn btn-outline-dark" %>
    <%
=begin%>
 編集対象のモデルオブジェクトを引数に渡す。　そのオブジェクトを編集するためのURLを出力してくれる。 
<%
=end%>
    <%= link_to "編集" ,edit_board_path(@board) , class:"btn btn-outline-dark" %>
  </div>
</div>

<%
=begin%>
 パーシャルを呼ぶ 
 renderするものがboardでmodel名と同じ(modelのオブジェクトと言うこと)ものは省略できる。今回は@boardだけ書き、こいつを渡す。
<%
=end%>

<%= render @board %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class ="container">
    <%= yield %>
  </div>
  </body>
</html>